server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/authService
    username: root
    password: Mango@1111

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true